baseURL = ""
languageCode = "en-us"
title = "Web Type"
theme = "type"

sectionPagesMenu = "main"
pygmentsUseClasses = true

buildFuture = true
buildDrafts = true

[markup.goldmark.renderer]
unsafe = true

